### ISSUE TITLE
Unable to build on Mac OSX Yosemite

### ISSUE THREAD

**Issue by ckarthikv** [cine-io/android-ffmpeg-with-rtmp#7]
The terminal shows:
.../android-ffmpeg-with-rtmp/.build-config.sh: line 2: Development: command not found

The build environment is -
OS_ARCH=darwin-x86_64
NDK=.../Android Development Kit/android-ndk-r10c
SYSROOT=.../Android Development Kit/android-ndk-r10c/platforms/android-19/arch-arm
TOOLCHAIN=.../Android Development Kit/android-ndk-r10c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64

Please help. Thanks.

**Comment by jeffreywescott** [comment]
@ckarthikv -- a few things:
1. Due to #6, right now these scripts only work with the Android NDK version r10 (not r10c).
2. Your particular issue looks odd. I'm guessing it's because your directory has spaces in the names. I'd need to look at your `.build-config.sh` to be sure, but you might try reconfiguring using a directory that has no spaces in the names ("Android-Development-Kit" instead of "Android Development Kit").

If you get it working with r10c, we'd love a pull-request!
