### ISSUE TITLE
Does this have x264 support?

### ISSUE THREAD

**Issue by ckarthikv** [cine-io/android-ffmpeg-with-rtmp#8]
Please let me know if this project has x264 support already built in?
If not, how do I add that?

Many thanks for the help.

**Comment by jeffreywescott** [comment]
It does, via libx264.

Right now what's needed is a pull request to add support for the latest NDK.

**Comment by ckarthikv** [comment]
Thanks Jeffrey. Post building, I only got the following libraries and there was no libx264 in that list - 
libavcodec-55.so
libavdevice-55.so
libavfilter-4.so
libavformat-55.so
libavutil-52.so
libcrypto.so
librtmp-1.so
libssl.so
libswresample-0.so
libswscale-2.so

Am I missing out on something? Should I change the configure file and rebuild it for x264 support? Pls let me know how to do the same. Thanks.

**Comment by jeffreywescott** [comment]
Sorry, @ckarthikv ... my bad. I remembered that incorrectly; you're right -- we're not including libx264, because most android devices (phones, tablets) have an h.264 encoder built-in that uses the GPU for hardware-accelerated encoding. This is necessary because h.264 encoding is incredibly CPU-intensive, and would drain the battery very quickly.

If you still want / need libx264, you'd first need to extend the scripts to go out and download the library, then you'd have to figure out how to cross-compile it for Android. Then you'd have to include libx264 when building FFmpeg.

Hopefully this gives you some hints as to how to start. Please submit a PR if you get it working!

Cheers.
